#!/usr/bin/env bash
# This file contains scripts to run the YouTube Downloader
# It's for reference - actual scripts are .bat (Windows) and .sh (macOS/Linux)

echo "YouTube Video Downloader - Setup Instructions"
echo "=============================================="
echo ""
echo "📖 DOCUMENTATION:"
echo "   1. Start here: 00_START_HERE.txt or INDEX.md"
echo "   2. Quick commands: QUICK_START.md"
echo "   3. Full setup: FULL_SETUP_GUIDE.md"
echo "   4. Complete docs: PROJECT_OVERVIEW.md"
echo "   5. Architecture: VISUAL_GUIDE.md"
echo ""
echo "🚀 QUICK START:"
echo ""
echo "WINDOWS:"
echo "   1. setup.bat"
echo "   2. start_backend.bat (Terminal 1)"
echo "   3. start_frontend.bat (Terminal 2)"
echo "   4. Open: http://127.0.0.1:5173"
echo ""
echo "MACOS/LINUX:"
echo "   1. chmod +x setup.sh && ./setup.sh"
echo "   2. chmod +x start_backend.sh && ./start_backend.sh (Terminal 1)"
echo "   3. chmod +x start_frontend.sh && ./start_frontend.sh (Terminal 2)"
echo "   4. Open: http://127.0.0.1:5173"
echo ""
echo "📁 PROJECT STRUCTURE:"
echo "   backend/          - FastAPI server"
echo "   frontend/         - Vue 3 UI"
echo "   *.bat/*.sh        - Setup & run scripts"
echo "   *.md/*.txt        - Documentation"
echo ""
echo "✨ FEATURES:"
echo "   ✓ Beautiful glasmorphism UI"
echo "   ✓ Download YouTube videos"
echo "   ✓ Select video quality"
echo "   ✓ Automatic audio merging"
echo "   ✓ MP4 output"
echo "   ✓ Download history"
echo "   ✓ Progress tracking"
echo "   ✓ Error handling"
echo ""
echo "📋 SCRIPTS:"
echo "   setup.bat/sh              - One-time setup"
echo "   start_backend.bat/sh      - Launch backend"
echo "   start_frontend.bat/sh     - Launch frontend"
echo "   build_production.bat/sh   - Production build"
echo ""
echo "✅ READY TO USE!"
echo ""
